name: CI
on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: |
        docker build .
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        pip install .
        pip install -r dev-requirements.txt
    - name: Run tests
      run: |
        pytest
    - name: Lint
      run: |
        flake8 -v
        black -v --check .
    - name: Type check
      run: |
        mypy allennlp_server --ignore-missing-imports --no-strict-optional --no-site-packages
    - name: Check package setup
      run: |
        python setup.py check
